import Vue from 'vue';
import BaseModal from "@/view/widget/Base/BaseModal.vue";
import BaseTable from "@/view/widget/Base/BaseTable.vue";
import BaseCardLayout from "@/view/widget/Base/BaseCardLayout.vue";
import BaseSqaureButton from "@/view/widget/Base/BaseSqaureButton.vue";
import BaseTextField from "@/view/widget/Base/BaseTextField.vue";
import BaseKeyValueSimpleTable from "@/view/widget/Base/BaseKeyValueSimpleTable.vue";
import BaseSelect from "@/view/widget/Base/BaseSelect.vue";
import BaseTextArea from "@/view/widget/Base/BaseTextArea.vue";
import BaseButton from "@/view/widget/Base/BaseButton.vue";
import BaseFilePicker from "@/view/widget/Base/BaseFilePicker.vue";

Vue.component('base-modal', BaseModal);
Vue.component('base-card-layout', BaseCardLayout);
Vue.component('base-text-field', BaseTextField);
Vue.component('base-text-area', BaseTextArea);
Vue.component('base-table', BaseTable);
Vue.component('base-square-button', BaseSqaureButton);
Vue.component('base-square-button', BaseSqaureButton);
Vue.component('base-simple-table', BaseKeyValueSimpleTable);
Vue.component('base-select', BaseSelect);
Vue.component('base-button', BaseButton);
Vue.component('base-file-picker', BaseFilePicker);
